export const Details=[{id:1,
    name: "Mufasa the lion king",
   img: "/images/mufasa.jpg", 
   genre: "action, drama",
   youtubeId: "aow3If0roo0",
},
{id:2,
     name: "viduthalai 2",
    img: "/images/viduthalai 2.jpg", 
    genre: "action, drama",
    youtubeId: "HOxXrrwa_8o"
},
{id:3,
    name: "pushpa 2", 
    img: "/images/pushpa 2.jpg",
    genre: "action, drama",
     youtubeId: "HtmlDoXttNg"
},
{id:4,
    name: "max",
    img: "/images/max.jpg", 
    genre: "action, drama",
    youtubeId: "nkY7cQ9NlTw"
},
{id:5,
    name: "Demonty colony",
    img: "/images/demonty.jpg", 
    genre: "action, drama",
    youtubeId: "Lnf8EsVGFno"
},
{id:6,
    name: "Thalapathy",
    img: "/images/thalapathy.jpg", 
    genre: "action, drama",
    youtubeId: "wA30CKor18A"
},
{id:7,
    name: "Amaran",
    img: "/images/amaran.jpg", 
    genre: "action, drama",
    youtubeId: "UPKLS4pRnSo"
},
{id:8,
    name: "Goat",
    img: "/images/goat.jpg", 
    genre: "action, drama",
    youtubeId: "jxCRlebiebw"
},

]